server.port = 8082

spring.application.name=kafka-consumer

spring.kafka.bootstrap-servers=localhost:9092

# Kafka Consumer Properties
# This Key-Value pair of configurations is used to give a unique id for the consumer groups.
spring.kafka.consumer.group-id=aircraft-consumer-group
# If no Offset exists for the consumer group then start reading from beginning.
spring.kafka.consumer.auto-offset-reset= earliest
spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer= org.springframework.kafka.support.serializer.JsonDeserializer

#Using this configuration on those POJO class objects are been Deserialized.
spring.kafka.consumer.properties.spring.json.trusted.packages=com.message.kafka.dto