spring.application.name=kafka-producer

#Kafka producer configurations
spring.kafka.producer.bootstrap-servers=localhost:9092

# This configurations helps to Serialize the String and Java objects into Json Objects.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

